name: QuantumCraft
version: '${version}'
main: ca.xef5000.quantumcraft.QuantumCraft
api-version: '1.20'
description: 'A plugin for creating and managing the quantum superposition of regions in Minecraft.'
authors: [xef5000]
depend: [ProtocolLib]
softdepend: [Vault, PlaceholderAPI, Quests]

commands:
  quantumcraft:
    description: Main command for QuantumCraft plugin
    aliases: [qc]
    usage: /quantumcraft <subcommand> [args...]
    permission: quantumcraft.admin

permissions:
  quantumcraft.admin:
    description: Allows access to all QuantumCraft commands
    default: op